src/Entity/Rune.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RuneRepository")
 */
class Rune
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $req_level;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $weapon;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $armor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $recipe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReqLevel(): ?int
    {
        return $this->req_level;
    }

    public function setReqLevel(int $req_level): self
    {
        $this->req_level = $req_level;

        return $this;
    }

    public function getWeapon(): ?string
    {
        return $this->weapon;
    }

    public function setWeapon(string $weapon): self
    {
        $this->weapon = $weapon;

        return $this;
    }

    public function getArmor(): ?string
    {
        return $this->armor;
    }

    public function setArmor(string $armor): self
    {
        $this->armor = $armor;

        return $this;
    }

    public function getRecipe(): ?string
    {
        return $this->recipe;
    }

    public function setRecipe(string $recipe): self
    {
        $this->recipe = $recipe;

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Rune;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="main")
     */
    public function index()
    {
        return $this->render('main/index.html.twig', [
            'title' => 'Главная страница',
        ]);
    }

    /**
     * @Route("/runes", name="runes")
     */
    public function runes()
    {
        return $this->render('main/runes.html.twig', [
            'title' => 'Руны',
            'runes' => $this->getDoctrine()->getRepository(Rune::class)->findAll()
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Главная страница{% endblock %}

{% block body %}
{% endblock %}

templates/main/runes.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th>Название</th>
                <th>Требуемый уровень</th>
                <th>Эффект в оружии</th>
                <th>Эффект в броне</th>
                <th>Рецепт для Хорадр. куба</th>
            </tr>
        </thead>
        {% for rune in runes %}
            <tr>
                <td>{{ rune.name }}</td>
                <td>{{ rune.reqLevel }}</td>
                <td>{{ rune.weapon }}</td>
                <td>{{ rune.armor }}</td>
                <td>{{ rune.recipe }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}